### ISSUE TITLE
python3.5 fix for subprocess

### ISSUE THREAD

**Issue by robgil** [python-cmd2/cmd2#27]
AttributeError: module 'subprocess' has no attribute 'mswindows'

This has been changed to _mswindows. Otherwise everything seems to work in 3.5. Still testing though

**Comment by robgil** [comment]
This looks fixed in 0.6.9a. Can you add to pip?

```
$ pip install -U cmd2==0.6.9a
Collecting cmd2==0.6.9a
  Could not find a version that satisfies the requirement cmd2==0.6.9a (from versions: 0.6.0.py3, 0.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.4.1, 0.3.5, 0.3.6, 0.3.7, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.5.1, 0.6.6, 0.6.6.1, 0.6.7, 0.6.8)
No matching distribution found for cmd2==0.6.9a
```

**Comment by FedericoCeratto** [comment]
0.6.9 has been released.
